name: 'Publish (pre-release)'

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'version type (use prerelease for bumping pre-release version):'
        required: true
        type: choice
        default: 'prerelease'
        options:
          - prepatch
          - preminor
          - premajor
          - prerelease
      npm_tag:
        required: true
        description: 'NPM tag:'
        type: choice
        default: 'beta'
        options:
          - alpha
          - beta
          - rc
      custom_version:
        description: 'use syntax x.y.z-beta.0, without "v" (it ignore "version type" parameter):'
        required: false

run-name: Publish ${{ inputs.new_version }} vk-mini-apps-router ${{ inputs.custom_version }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@vkontakte'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
        shell: bash

      - name: Set Git credentials
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
        shell: bash

      - name: Bump version
        id: updated_versions_info
        uses: ./.github/actions/bump-version
        with:
          version: ${{ github.event.inputs.custom_version || github.event.inputs.new_version }}
          npm_tag: ${{ github.event.inputs.npm_tag }}

      - name: Validation
        uses: ./.github/actions/validation

      - name: Publish to npm
        run: npm publish --access public --tag ${{ github.event.inputs.npm_tag }}
        shell: bash

      - name: Commit and tag version bump
        run: |
          git add package.json
          git commit -m "bump(vk-mini-apps-router): from ${{ steps.updated_versions_info.outputs.prev_version }} to ${{ steps.updated_versions_info.outputs.next_version }}"
          git tag vk-mini-apps-router@${{ steps.updated_versions_info.outputs.next_version }}
        shell: bash

      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
